language: node_js
node_js: "8"
install:
  - npm install
jobs:
  include:
    - stage: unit tests with coverage
      script: yarn coverage
    - stage: build
      script: yarn build
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: "kpfromer2@gmail.com"
        api_key: $NPM_API_KEY
      on: npm-release
