language: node_js
node_js: "8"
install:
  - npm install
jobs:
  include:
    - stage: lint
      script: yarn run lint
    - stage: unit tests
      script: yarn run coverage
    - stage: build
      script: yarn run build
    - stage: npm release
      if: branch IN (npm-release) AND NOT type IN (pull_request) # this is that travis dosnt create a "deploy" job in an commit other than in "npm-release"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: "kpfromer2@gmail.com"
        api_key: $NPM_API_KEY
      on: npm-release
